name: bmkg_gempa
description: Dart client library untuk mendapat data gempabumi dari situs data terbuka BMKG.
version: 1.0.2
repository: https://github.com/rmRizki/bmkg_gempa

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  