name: bmkg_gempa
description: Dart client library untuk mendapat data gempabumi dari situs data terbuka BMKG.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  